services:
  journey-sync-self-hosted-service:
    image: journeycloud/journey-sync-self-hosted
    labels:
      kompose.volume.size: 4Gi
    environment:
      EXPRESS_SERVER_PORT: 8080
      REDIS_PORT: 6379
      DISABLE_SSL: NO
      DOMAIN: mydomain.com
      ROOT_MONGO_DB_URL: mongodb://root:password@journey-mongodb-service:27017
      MONGO_DB_URL: mongodb://user:password@journey-mongodb-service:27017/journey
      REDIS_URL: redis://journey-redis-service:6379
      FS_PATH: /mnt/data
      SIGNED: randomalphanumeric1
      ADMIN_JS_COOKIE_PASSWORD: randomalphanumeric2
      TYPESENSE_HOST: journey-typesense-service
      TYPESENSE_PORT: 8108
      TYPESENSE_PROTOCOL: http
      TYPESENSE_API_KEY: xyz
    entrypoint: 'npm run launch'
    depends_on:
      - journey-mongodb-service
      - journey-redis-service
      - journey-typesense-service
    volumes:
      - journey-fs-volume:/mnt/data
    ports:
      - 8080:8080
  journey-sync-self-hosted-media:
    image: journeycloud/journey-sync-self-hosted
    labels:
      kompose.volume.size: 4Gi
    environment:
      REDIS_PORT: 6379
      DISABLE_SSL: NO
      DOMAIN: mydomain.com
      ROOT_MONGO_DB_URL: mongodb://root:password@journey-mongodb-service:27017
      MONGO_DB_URL: mongodb://user:password@journey-mongodb-service:27017/journey
      REDIS_URL: redis://journey-redis-service:6379
      FS_PATH: /mnt/data
    entrypoint: 'npm run launchMedia'
    depends_on:
      - journey-sync-self-hosted-service
    volumes:
      - journey-fs-volume:/mnt/data
  journey-mongodb-service:
    image: mongo:7.0
    labels:
      kompose.volume.size: 4Gi
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: journey
    volumes:
      - journey-mongodb-volume:/data/db
  journey-redis-service:
    image: redis:7.2.4-alpine
    labels:
      kompose.volume.size: 4Gi
    volumes:
      - journey-redis-volume:/data
    command: redis-server
  journey-typesense-service:
    image: typesense/typesense:26.0
    labels:
      kompose.volume.size: 10Gi
    volumes:
      - journey-typesense-volume:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
volumes:
  journey-mongodb-volume:
    labels:
      kompose.volume.size: 10Gi
  journey-typesense-volume:
    labels:
      kompose.volume.size: 10Gi
  journey-fs-volume:
    labels:
      kompose.volume.size: 20Gi
  journey-redis-volume:
    labels:
      kompose.volume.size: 4Gi